edition = "2021"
chain_width = 75
max_width = 100
hard_tabs = true
newline_style = "Unix"
reorder_imports = false
reorder_modules = false
use_try_shorthand = true
use_field_init_shorthand = true
match_block_trailing_comma = true
match_arm_leading_pipes = "Preserve"